###欢迎界面
GET {{host}}:{{port}}/home/

###项目列表
GET {{host}}:{{port}}/home/items

###设置项目列表
POST {{host}}:{{port}}/home/items
content-type: application/json

{
  "list": [
    "设置项目1",
    "项目2",
    "项目3"
  ]
}

###添加项目
PUT {{host}}:{{port}}/home/items?item=选项4

###删除项目
DELETE {{host}}:{{port}}/home/items?item=选项3
